Name=input('enter name:')
Age=int(input('enter age:'))
College=input('enter college name:')
Branch=input('enter branch:')
CGPA=float(input('enter cgpa:'))
print('========== STUDENT PROFILE ==========')
print('Name    : ',Name)
print('Age     : ',Age)
print('College : ',College)
print('Branch  : ',Branch)
print('CGPA    : ',CGPA)